// Generated by tools/generate-config-layout.py from Sources/FotufilmHalide/config-layout.json.
#ifndef FOTUFILM_CONFIG_LAYOUT_H
#define FOTUFILM_CONFIG_LAYOUT_H

enum {
    FOTUFILM_COUPLER_WARP_SAMPLES = 128,
    FOTUFILM_COUPLER_WARP_MIN = -4,
    FOTUFILM_COUPLER_WARP_MAX = 4,
    FOTUFILM_TONE_GRID_EDGE = 64,
    FOTUFILM_TONE_GRID_CELLS = FOTUFILM_TONE_GRID_EDGE * FOTUFILM_TONE_GRID_EDGE,
    FOTUFILM_SAMPLED_CURVE_MAX_SAMPLES = 1024,
    FOTUFILM_SAMPLED_CURVE_STRIDE = 1 + 3 * FOTUFILM_SAMPLED_CURVE_MAX_SAMPLES,
    /// Crystal size bins per record in the crystal grain model: coated sublayers from the fastest,
    /// coarsest crystals down to the slowest, finest.
    FOTUFILM_CRYSTAL_GRAIN_BINS = 4,
    /// Samples per bin of the crystal grain model's developed-count table, against the record's
    /// developed density as a fraction of its range, 0...1.
    FOTUFILM_CRYSTAL_GRAIN_SAMPLES = 64,
    /// Texels per side of the film grain model's seamless tile; a texel is a micron of film.
    FOTUFILM_FILM_TILE_SIDE = 256,
    /// Gross densities, D-min to D-max, the film grain model renders each record's tile at.
    FOTUFILM_FILM_TILE_LEVELS = 17,
    /// Side, in texels, of the film blocks that each take the tile at their own hashed offset and
    /// orientation.
    FOTUFILM_FILM_TILE_BLOCK = 64,
};

enum {
    FOTUFILM_CONFIG_CURVES = 0,
    FOTUFILM_CONFIG_HALATION = 18,
    FOTUFILM_CONFIG_COUPLER = 21,
    FOTUFILM_CONFIG_GRAIN = 30,
    FOTUFILM_CONFIG_PAPER = 33,
    FOTUFILM_CONFIG_MASKING = 39,
    FOTUFILM_CONFIG_MTF_SIGMA = 42,
    FOTUFILM_CONFIG_MTF_RADIUS = 45,
    FOTUFILM_CONFIG_HALATION_RADIUS = 48,
    FOTUFILM_CONFIG_COUPLER_SIGMA = 51,
    FOTUFILM_CONFIG_COUPLER_RADIUS = 52,
    FOTUFILM_CONFIG_ADJACENCY_SIGMA = 53,
    FOTUFILM_CONFIG_ADJACENCY_RADIUS = 54,
    FOTUFILM_CONFIG_GRAIN_SIGMA = 55,
    FOTUFILM_CONFIG_GRAIN_RADIUS = 56,
    FOTUFILM_CONFIG_FLARE = 57,
    FOTUFILM_CONFIG_COUPLER_SCALE = 58,
    FOTUFILM_CONFIG_ADJACENCY_STRENGTH = 59,
    FOTUFILM_CONFIG_GRAIN_LAMBDA = 60,
    FOTUFILM_CONFIG_EXPOSURE_GAIN = 61,
    FOTUFILM_CONFIG_PAPER_MIDPOINT = 62,
    FOTUFILM_CONFIG_FLARE_MEAN = 63,
    FOTUFILM_CONFIG_COUPLER_WARP = 66,
    FOTUFILM_CONFIG_WHITE_BALANCE = 450,
    FOTUFILM_CONFIG_HIGHLIGHTS = 453,
    FOTUFILM_CONFIG_SHADOWS = 454,
    FOTUFILM_CONFIG_SATURATION = 455,
    FOTUFILM_CONFIG_VIBRANCE = 456,
    FOTUFILM_CONFIG_HALATION_KERNEL = 457,
    FOTUFILM_CONFIG_GRAIN_CORRELATION = 466,
    FOTUFILM_CONFIG_MTF_LUMA_SHARE = 467,
    FOTUFILM_CONFIG_MTF_LUMA_SIGMA = 468,
    FOTUFILM_CONFIG_MTF_LUMA_RADIUS = 469,
    FOTUFILM_CONFIG_GRADE_LIFT = 470,
    FOTUFILM_CONFIG_GRADE_GAIN = 473,
    FOTUFILM_CONFIG_GRADE_INV_GAMMA = 476,
    FOTUFILM_CONFIG_FRAME_WIDTH = 479,
    FOTUFILM_CONFIG_FRAME_HEIGHT = 480,
    FOTUFILM_CONFIG_TONE_GRID_WIDTH = 481,
    FOTUFILM_CONFIG_TONE_GRID_HEIGHT = 482,
    FOTUFILM_CONFIG_TONE_GRID_A = 483,
    FOTUFILM_CONFIG_TONE_GRID_B = 4579,
    /// Non-zero to develop grain as a Boolean model of discs rather than as a blurred clump field.
    FOTUFILM_CONFIG_GRAIN_MODE = 8675,
    /// Grain radius in pixels. The Boolean path is only taken once this reaches a pixel, below
    /// which the clump field is already the model's own limit and far cheaper.
    FOTUFILM_CONFIG_GRAIN_DISC_RADIUS = 8676,
    /// Per-layer density amplitude for the Boolean path, calibrated so the covered fraction read
    /// through a 48 um aperture carries the stock's published granularity.
    FOTUFILM_CONFIG_GRAIN_DISC = 8677,
    /// Non-zero to run the three-way grade on the sRGB-encoded signal, the way a grading suite's
    /// three-way corrector does, rather than on display-linear light. Appended last so that adding
    /// it renumbered nothing.
    FOTUFILM_CONFIG_GRADE_SPACE = 8680,
    /// The grain-size mixture's second clump field — the soft mottle the coarse crystal population
    /// lays under the sharp grain. Blur sigma and radius in pixels, the coarse population's own
    /// clumps-per-pixel, and per-layer density amplitudes[3] carrying that component's share of the
    /// published granularity. Appended last so that adding them renumbered nothing.
    FOTUFILM_CONFIG_MOTTLE_SIGMA = 8681,
    FOTUFILM_CONFIG_MOTTLE_RADIUS = 8682,
    FOTUFILM_CONFIG_MOTTLE_LAMBDA = 8683,
    FOTUFILM_CONFIG_MOTTLE = 8684,
    /// The paper's red and blue records, six curve parameters each, with the green record staying
    /// in the legacy FOTUFILM_CONFIG_PAPER slot; then the two records' own calibrated midpoints,
    /// the per-channel analogue of FOTUFILM_CONFIG_PAPER_MIDPOINT. A paper that publishes one curve
    /// packs it in all three slots. Appended last so that adding them renumbered nothing.
    FOTUFILM_CONFIG_PAPER_RED = 8687,
    FOTUFILM_CONFIG_PAPER_BLUE = 8693,
    FOTUFILM_CONFIG_PAPER_MIDPOINT_RED = 8699,
    FOTUFILM_CONFIG_PAPER_MIDPOINT_BLUE = 8700,
    /// Which granularity-against-density law the emulsion obeys. 0 is a chromogenic negative, whose
    /// measured curve peaks just above D-min and falls (the shape's coefficients are in
    /// FOTUFILM_CONFIG_GRAIN_DENSITY_PROFILE); 1 is opaque silver, whose Boolean aperture variance
    /// goes as `D * 10^(0.21004 D + 0.06114 D^2)`; 2 explicitly retains Selwyn's `sigma ∝ sqrt(D)`;
    /// 3 is dye reversal's saturating power law. Mirrors `GrainDensityLaw`.
    FOTUFILM_CONFIG_GRAIN_LAW = 8701,
    /// Per-layer net density the stock's published granularity is read at, and the per-layer
    /// developed fog added to both that anchor and the pixel's own density. The fog is what keeps
    /// granularity finite rather than zero where the negative is clear.
    FOTUFILM_CONFIG_GRAIN_ANCHOR = 8702,
    FOTUFILM_CONFIG_GRAIN_FOG = 8705,
    /// Per-layer blur sigma in pixels for the sharp grain field and for the coarse mottle. The
    /// blue-sensitive layer of a colour negative carries the coarsest crystals, so its grain is
    /// lower in frequency and not merely louder. FOTUFILM_CONFIG_GRAIN_RADIUS and
    /// FOTUFILM_CONFIG_MOTTLE_RADIUS stay scalar: they are the widest of the three kernels, and the
    /// narrower ones have decayed to nothing out there.
    FOTUFILM_CONFIG_GRAIN_SIGMA_LAYER = 8708,
    FOTUFILM_CONFIG_MOTTLE_SIGMA_LAYER = 8711,
    /// Gaussian sigma and radius, in pixels, of the enlarger lens and the paper's own light
    /// scattering. It acts on the light the negative transmits, so the pipeline applies it in
    /// transmittance rather than in density.
    FOTUFILM_CONFIG_PRINT_MTF_SIGMA = 8714,
    FOTUFILM_CONFIG_PRINT_MTF_RADIUS = 8715,
    /// Optional final row-major matrix, transfer, and premultiplication used by
    /// FOTUFILM_FRAME_ENCODE_OUT. Other variants return display-linear light.  0  identity — the
    /// host's space is already linear. 1  power law, sign-preserving: |v| <= c4 ? |v| * c0 : c1 *
    /// pow(|v|, c2) + c3, carried back across zero by the sign. Rec.709 gamma 2.4 and sRGB. 2
    /// logarithmic, signed: v <= c4 ? v * c0 + c3 : c1 * log2(v + c5) + c2. DaVinci Intermediate
    /// and ACEScct.  `fotufilm::outputTransformFor` defines the coefficients.
    FOTUFILM_CONFIG_OUTPUT_MATRIX = 8716,
    FOTUFILM_CONFIG_OUTPUT_TRANSFER = 8725,
    FOTUFILM_CONFIG_OUTPUT_COEFFICIENTS = 8726,
    FOTUFILM_CONFIG_OUTPUT_PREMULTIPLIED = 8732,
    /// The share of the detail under the print MTF's blur the finish returns, 0...1. An enlarger
    /// keeps 0; a scan finish keeps most of it, because a minilab sharpens its read. Appended after
    /// the output transform so that adding it renumbered nothing.
    FOTUFILM_CONFIG_PRINT_SHARPEN = 8733,
    /// The lens diffusion filter — mist, fog, black mist — which is the only stage that runs ahead
    /// of the emulsion, because the filter it models is screwed onto the front of the lens.
    /// Appended last so that adding it renumbered nothing.  The share of the beam that reached the
    /// film without meeting a particle. Perfectly sharp, and what keeps a diffused picture from
    /// looking defocused.
    FOTUFILM_CONFIG_DIFFUSION_DIRECT = 8734,
    /// How much of the scattered light each of the three scales carries, per record: `[record * 3 +
    /// scale]`, already multiplied by the scattered share. The records differ because the
    /// scattering angle goes as the wavelength, so a red halo is wider than a blue one; a row
    /// summing to less than the scattered share is light that went past the widest scale, and it
    /// has already been added to FOTUFILM_CONFIG_FLARE rather than dropped.
    FOTUFILM_CONFIG_DIFFUSION_KERNEL = 8735,
    /// Pixel radius of each scale. Strides and strided radii are derived from these by the same
    /// `fotufilm_halation_stride` rule the halation pyramid uses.
    FOTUFILM_CONFIG_DIFFUSION_RADIUS = 8744,
    /// The donor capture layer — a coated layer that develops and releases inhibitor but forms no
    /// image dye of its own (REALA's 4th Color Layer). Six H&D parameters for its own development
    /// curve, then one release weight per dye-forming receiver, in the engine's R, G, B record
    /// order. Read only when FOTUFILM_FRAME_DONOR_LAYER is set; appended last so that adding them
    /// renumbered nothing.
    FOTUFILM_CONFIG_DONOR_CURVE = 8747,
    FOTUFILM_CONFIG_DONOR_RELEASE = 8753,
    /// Reserved legacy annular-basis radii. Continuous physical kernels leave these zero.
    FOTUFILM_CONFIG_HALATION_RING_RADIUS = 8756,
    /// Row-major 3x3 spectral halation return matrix, receiver rows by source columns, in the mix
    /// domain: entry [c][j] is the share of receiver c's developed exposure that arrives as source
    /// record j's base-returned light. Rows sum to the receiver's legacy mix share, so a diagonal
    /// of the old FOTUFILM_CONFIG_HALATION values reproduces the scalar mix exactly; the off-
    /// diagonal terms are what the per-wavelength stack transmission (the orange mask favouring
    /// deep red on the return trip) routes between records. The scalar shares at
    /// FOTUFILM_CONFIG_HALATION are still written but no longer read by the kernels.
    FOTUFILM_CONFIG_HALATION_MATRIX = 8759,
    /// Five parameters per dye-forming record for an optional second coated speed group: gamma,
    /// toe, toe width, shoulder, shoulder width. A zero gamma is the original six-parameter curve
    /// exactly. Appended so no existing configuration offset moves.
    FOTUFILM_CONFIG_CURVE_SECONDARY = 8768,
    /// A second positive Gaussian diffusion scale per record, followed by its radii and the primary
    /// scale's blend shares. Shares of one are the original single-Gaussian MTF exactly.
    FOTUFILM_CONFIG_MTF_SECONDARY_SIGMA = 8783,
    FOTUFILM_CONFIG_MTF_SECONDARY_RADIUS = 8786,
    FOTUFILM_CONFIG_MTF_PRIMARY_SHARE = 8789,
    /// Hill exponents for normalized inhibitor release by each dye-forming donor, followed by the
    /// optional donor-only layer's exponent. 1 is the historical linear law.
    FOTUFILM_CONFIG_COUPLER_RELEASE_GAMMA = 8792,
    FOTUFILM_CONFIG_DONOR_RELEASE_GAMMA = 8795,
    /// Lens-diffusion scale weights for the optional donor capture record. Kept separate from the
    /// three dye-forming rows above so existing configuration offsets remain fixed.
    FOTUFILM_CONFIG_DONOR_DIFFUSION_KERNEL = 8796,
    /// Whether development complements the formed density to a direct positive: 1 on a genuine
    /// reversal stock, 0 otherwise. Distinct from FOTUFILM_FRAME_REVERSAL, which also routes a
    /// negative shown on a light box or scanner past the paper; that negative is still developed as
    /// a negative, so its density law and its grain are evaluated in its own density.
    FOTUFILM_CONFIG_DEVELOP_COMPLEMENT = 8799,
    /// Superseded by FOTUFILM_CONFIG_GRAIN_DENSITY_RECORDS, which carries the shape per record with
    /// its second rise; still written with the green record's first three coefficients so a kernel
    /// built against the earlier layout renders the earlier law. Read only under
    /// FOTUFILM_CONFIG_GRAIN_LAW 0: the coarse sub-layer's variance amplitude, the toe density over
    /// which anything develops at all, and the density over which that coarse population decays
    /// onto the fine one.
    FOTUFILM_CONFIG_GRAIN_DENSITY_PROFILE = 8800,
    /// The knee of the SDR shoulder the delivery asks for, applied between the output matrix and
    /// the output transfer — the step `FilmOutputConversion` takes on the host, moved into the
    /// kernel so the encode variants can carry a shouldered delivery rather than only a bare one.
    /// Negative means no shoulder, which is the identity a linear or unshouldered space wants; 1
    /// leaves everything below display white alone and clips above it, which is what a print or
    /// scan bounded by its own white takes; 0.7 is a directly viewed transparency's. The host
    /// initialises it to the material's own knee, which the byte delivery reads, and an encode
    /// variant's `setOutputTransform` replaces it; appended without renumbering earlier fields.
    FOTUFILM_CONFIG_OUTPUT_SHOULDER = 8803,
    /// Enabled flag followed by three host-primary luminance weights. Fits chroma after the output
    /// matrix while preserving luminance and above-white highlights; zero disables it.
    FOTUFILM_CONFIG_OUTPUT_GAMUT = 8804,
    /// Three records: sample count, then (log exposure, density, tangent) triples.
    FOTUFILM_CONFIG_SAMPLED_CURVES = 8808,
    /// 0: Gaussian/log-exposure adjacency; 1: screened diffusion/Nelson density response.
    FOTUFILM_CONFIG_ADJACENCY_MODEL = 18027,
    FOTUFILM_CONFIG_ADJACENCY_SECONDARY_SIGMA = 18028,
    FOTUFILM_CONFIG_ADJACENCY_SECONDARY_RADIUS = 18029,
    /// Broad transport changes off-diagonal inhibition only; zero amount preserves legacy output.
    FOTUFILM_CONFIG_CHROMATIC_FRINGE_AMOUNT = 18030,
    FOTUFILM_CONFIG_CHROMATIC_FRINGE_SIGMA = 18031,
    FOTUFILM_CONFIG_CHROMATIC_FRINGE_RADIUS = 18032,
    /// Typed record-exposure input seam. Zero is ordinary scene input.
    FOTUFILM_CONFIG_RECORD_INPUT = 18033,
    /// Dye reversal's [exponent p, shoulder density Ds], read under grain law 3.
    FOTUFILM_CONFIG_GRAIN_REVERSAL_PROFILE = 18034,
    /// Crystal grain model, read under grain mode 2: per record and size bin, [lattice blur sigma
    /// of the bin's dye cloud in pixels, density one cloud adds to the pixel it lands in, the
    /// sublayer's coupler pool in density (0: silver, no pool), the mean-dye factor: the sum over
    /// the cloud's lattice taps of 1 - exp(-(density per cloud x tap) / pool), which by Campbell's
    /// theorem gives the expected dye of the Poisson field as pool (1 - exp(-count x factor)); for
    /// silver the density per cloud itself].
    FOTUFILM_CONFIG_CRYSTAL_GRAIN_BIN = 18036,
    /// Crystal grain model, exposure stage: per record and size bin, the mean count of latent
    /// (developable) crystals per pixel against the record's developed density as a fraction of its
    /// range, CRYSTAL_GRAIN_SAMPLES values from 0 to 1. Indexed by density rather than exposure so
    /// the split renderer's density-in tail can lay it; the curve is monotone, so the two say the
    /// same thing.
    FOTUFILM_CONFIG_CRYSTAL_GRAIN_LAMBDA = 18084,
    /// Crystal grain model, print stage: per record, how many of the print material's own crystals
    /// one output pixel holds at full development (0 when nothing exposes a paper: a viewed
    /// transparency, a scan, a screen, the negative itself), then the frame's hash seed as a float,
    /// for the print pipeline whose arguments carry none. The paper's developed count is a Poisson
    /// draw at the paper's developed fraction of that, and its departure from the mean is what the
    /// paper's own grain adds.
    FOTUFILM_CONFIG_CRYSTAL_PRINT_GRAIN = 18852,
    /// Uniform additive camera film preflash relative to metered mid-grey; 0 is off.
    FOTUFILM_CONFIG_CAMERA_PREFLASH = 18856,
    /// Uniform additive paper preflash relative to paper mid-exposure; 0 is off.
    FOTUFILM_CONFIG_PRINTER_PREFLASH = 18857,
    /// The primaries of the byte frames on the encoded-byte road, [input, output]: 0 Display P3, 1
    /// sRGB, both under the sRGB transfer. The decode steps the input basis into the working space;
    /// the delivery leaves the print's Display P3 for the output basis after the shoulder and
    /// before the clip. Read only on byte I/O; a float frame is the working space itself.
    FOTUFILM_CONFIG_BYTE_BASIS = 18858,
    /// The chromogenic negative's granularity-against-density shape per record, read only under
    /// FOTUFILM_CONFIG_GRAIN_LAW 0: for red, green and blue in turn, the coarse sub-layer's
    /// variance amplitude, the toe density over which anything develops at all, the density over
    /// which that coarse population decays onto the fine one, then the amplitude, centre density
    /// and width of the second rise where the slow sub-layer's coarse population comes in. Mirrors
    /// `FilmStock.grainDensityProfile`; appended without renumbering earlier fields.
    FOTUFILM_CONFIG_GRAIN_DENSITY_RECORDS = 18860,
    /// The film grain model (grain mode 3), sampled from its tiles: the pixel pitch in tile texels,
    /// the grain amount the tiles' grain is scaled by, the id the host registered the tiles under,
    /// each record's D-min then D-max (the range the levels span), then per record FILM_TILE_LEVELS
    /// each of the level's mean light, the mean density a pixel of this pitch reads there, and the
    /// correlation of its grain with the next level's at this pitch. Read only in grain mode 3;
    /// appended without renumbering earlier fields.
    FOTUFILM_CONFIG_FILM_TILE = 18878,
};

enum {
    FOTUFILM_CONFIG_CURVES_COUNT = 18,
    FOTUFILM_CONFIG_HALATION_COUNT = 3,
    FOTUFILM_CONFIG_COUPLER_COUNT = 9,
    FOTUFILM_CONFIG_GRAIN_COUNT = 3,
    FOTUFILM_CONFIG_PAPER_COUNT = 6,
    FOTUFILM_CONFIG_MASKING_COUNT = 3,
    FOTUFILM_CONFIG_MTF_SIGMA_COUNT = 3,
    FOTUFILM_CONFIG_MTF_RADIUS_COUNT = 3,
    FOTUFILM_CONFIG_HALATION_RADIUS_COUNT = 3,
    FOTUFILM_CONFIG_COUPLER_SIGMA_COUNT = 1,
    FOTUFILM_CONFIG_COUPLER_RADIUS_COUNT = 1,
    FOTUFILM_CONFIG_ADJACENCY_SIGMA_COUNT = 1,
    FOTUFILM_CONFIG_ADJACENCY_RADIUS_COUNT = 1,
    FOTUFILM_CONFIG_GRAIN_SIGMA_COUNT = 1,
    FOTUFILM_CONFIG_GRAIN_RADIUS_COUNT = 1,
    FOTUFILM_CONFIG_FLARE_COUNT = 1,
    FOTUFILM_CONFIG_COUPLER_SCALE_COUNT = 1,
    FOTUFILM_CONFIG_ADJACENCY_STRENGTH_COUNT = 1,
    FOTUFILM_CONFIG_GRAIN_LAMBDA_COUNT = 1,
    FOTUFILM_CONFIG_EXPOSURE_GAIN_COUNT = 1,
    FOTUFILM_CONFIG_PAPER_MIDPOINT_COUNT = 1,
    FOTUFILM_CONFIG_FLARE_MEAN_COUNT = 3,
    FOTUFILM_CONFIG_COUPLER_WARP_COUNT = 384,
    FOTUFILM_CONFIG_WHITE_BALANCE_COUNT = 3,
    FOTUFILM_CONFIG_HIGHLIGHTS_COUNT = 1,
    FOTUFILM_CONFIG_SHADOWS_COUNT = 1,
    FOTUFILM_CONFIG_SATURATION_COUNT = 1,
    FOTUFILM_CONFIG_VIBRANCE_COUNT = 1,
    FOTUFILM_CONFIG_HALATION_KERNEL_COUNT = 9,
    FOTUFILM_CONFIG_GRAIN_CORRELATION_COUNT = 1,
    FOTUFILM_CONFIG_MTF_LUMA_SHARE_COUNT = 1,
    FOTUFILM_CONFIG_MTF_LUMA_SIGMA_COUNT = 1,
    FOTUFILM_CONFIG_MTF_LUMA_RADIUS_COUNT = 1,
    FOTUFILM_CONFIG_GRADE_LIFT_COUNT = 3,
    FOTUFILM_CONFIG_GRADE_GAIN_COUNT = 3,
    FOTUFILM_CONFIG_GRADE_INV_GAMMA_COUNT = 3,
    FOTUFILM_CONFIG_FRAME_WIDTH_COUNT = 1,
    FOTUFILM_CONFIG_FRAME_HEIGHT_COUNT = 1,
    FOTUFILM_CONFIG_TONE_GRID_WIDTH_COUNT = 1,
    FOTUFILM_CONFIG_TONE_GRID_HEIGHT_COUNT = 1,
    FOTUFILM_CONFIG_TONE_GRID_A_COUNT = 4096,
    FOTUFILM_CONFIG_TONE_GRID_B_COUNT = 4096,
    FOTUFILM_CONFIG_GRAIN_MODE_COUNT = 1,
    FOTUFILM_CONFIG_GRAIN_DISC_RADIUS_COUNT = 1,
    FOTUFILM_CONFIG_GRAIN_DISC_COUNT = 3,
    FOTUFILM_CONFIG_GRADE_SPACE_COUNT = 1,
    FOTUFILM_CONFIG_MOTTLE_SIGMA_COUNT = 1,
    FOTUFILM_CONFIG_MOTTLE_RADIUS_COUNT = 1,
    FOTUFILM_CONFIG_MOTTLE_LAMBDA_COUNT = 1,
    FOTUFILM_CONFIG_MOTTLE_COUNT = 3,
    FOTUFILM_CONFIG_PAPER_RED_COUNT = 6,
    FOTUFILM_CONFIG_PAPER_BLUE_COUNT = 6,
    FOTUFILM_CONFIG_PAPER_MIDPOINT_RED_COUNT = 1,
    FOTUFILM_CONFIG_PAPER_MIDPOINT_BLUE_COUNT = 1,
    FOTUFILM_CONFIG_GRAIN_LAW_COUNT = 1,
    FOTUFILM_CONFIG_GRAIN_ANCHOR_COUNT = 3,
    FOTUFILM_CONFIG_GRAIN_FOG_COUNT = 3,
    FOTUFILM_CONFIG_GRAIN_SIGMA_LAYER_COUNT = 3,
    FOTUFILM_CONFIG_MOTTLE_SIGMA_LAYER_COUNT = 3,
    FOTUFILM_CONFIG_PRINT_MTF_SIGMA_COUNT = 1,
    FOTUFILM_CONFIG_PRINT_MTF_RADIUS_COUNT = 1,
    FOTUFILM_CONFIG_OUTPUT_MATRIX_COUNT = 9,
    FOTUFILM_CONFIG_OUTPUT_TRANSFER_COUNT = 1,
    FOTUFILM_CONFIG_OUTPUT_COEFFICIENTS_COUNT = 6,
    FOTUFILM_CONFIG_OUTPUT_PREMULTIPLIED_COUNT = 1,
    FOTUFILM_CONFIG_PRINT_SHARPEN_COUNT = 1,
    FOTUFILM_CONFIG_DIFFUSION_DIRECT_COUNT = 1,
    FOTUFILM_CONFIG_DIFFUSION_KERNEL_COUNT = 9,
    FOTUFILM_CONFIG_DIFFUSION_RADIUS_COUNT = 3,
    FOTUFILM_CONFIG_DONOR_CURVE_COUNT = 6,
    FOTUFILM_CONFIG_DONOR_RELEASE_COUNT = 3,
    FOTUFILM_CONFIG_HALATION_RING_RADIUS_COUNT = 3,
    FOTUFILM_CONFIG_HALATION_MATRIX_COUNT = 9,
    FOTUFILM_CONFIG_CURVE_SECONDARY_COUNT = 15,
    FOTUFILM_CONFIG_MTF_SECONDARY_SIGMA_COUNT = 3,
    FOTUFILM_CONFIG_MTF_SECONDARY_RADIUS_COUNT = 3,
    FOTUFILM_CONFIG_MTF_PRIMARY_SHARE_COUNT = 3,
    FOTUFILM_CONFIG_COUPLER_RELEASE_GAMMA_COUNT = 3,
    FOTUFILM_CONFIG_DONOR_RELEASE_GAMMA_COUNT = 1,
    FOTUFILM_CONFIG_DONOR_DIFFUSION_KERNEL_COUNT = 3,
    FOTUFILM_CONFIG_DEVELOP_COMPLEMENT_COUNT = 1,
    FOTUFILM_CONFIG_GRAIN_DENSITY_PROFILE_COUNT = 3,
    FOTUFILM_CONFIG_OUTPUT_SHOULDER_COUNT = 1,
    FOTUFILM_CONFIG_OUTPUT_GAMUT_COUNT = 4,
    FOTUFILM_CONFIG_SAMPLED_CURVES_COUNT = 9219,
    FOTUFILM_CONFIG_ADJACENCY_MODEL_COUNT = 1,
    FOTUFILM_CONFIG_ADJACENCY_SECONDARY_SIGMA_COUNT = 1,
    FOTUFILM_CONFIG_ADJACENCY_SECONDARY_RADIUS_COUNT = 1,
    FOTUFILM_CONFIG_CHROMATIC_FRINGE_AMOUNT_COUNT = 1,
    FOTUFILM_CONFIG_CHROMATIC_FRINGE_SIGMA_COUNT = 1,
    FOTUFILM_CONFIG_CHROMATIC_FRINGE_RADIUS_COUNT = 1,
    FOTUFILM_CONFIG_RECORD_INPUT_COUNT = 1,
    FOTUFILM_CONFIG_GRAIN_REVERSAL_PROFILE_COUNT = 2,
    FOTUFILM_CONFIG_CRYSTAL_GRAIN_BIN_COUNT = 48,
    FOTUFILM_CONFIG_CRYSTAL_GRAIN_LAMBDA_COUNT = 768,
    FOTUFILM_CONFIG_CRYSTAL_PRINT_GRAIN_COUNT = 4,
    FOTUFILM_CONFIG_CAMERA_PREFLASH_COUNT = 1,
    FOTUFILM_CONFIG_PRINTER_PREFLASH_COUNT = 1,
    FOTUFILM_CONFIG_BYTE_BASIS_COUNT = 2,
    FOTUFILM_CONFIG_GRAIN_DENSITY_RECORDS_COUNT = 18,
    FOTUFILM_CONFIG_FILM_TILE_COUNT = 162,
};

enum { FOTUFILM_FRAME_CONFIGURATION_COUNT = 19040 };

#endif
