// Generated by tools/generate-aot-variants.py from Sources/FotufilmHalide/aot-variants.json.
#ifndef FOTUFILM_AOT_VARIANTS_H
#define FOTUFILM_AOT_VARIANTS_H

/// Full spatial-stage mask, including post-grain enlarger blur. Zero radius makes enlarger blur
/// identity, avoiding a separate variant family. Capture glare remains opt-in through
/// `FOTUFILM_AOT_FLARE` because most input has already passed through a lens.
#define FOTUFILM_AOT_ALL_STAGES ((FOTUFILM_FRAME_MTF | FOTUFILM_FRAME_MTF_LUMA | FOTUFILM_FRAME_HALATION | FOTUFILM_FRAME_COUPLERS | FOTUFILM_FRAME_COUPLER_DIFFUSION | FOTUFILM_FRAME_ADJACENCY | FOTUFILM_FRAME_GRAIN | FOTUFILM_FRAME_PRINT_MTF | FOTUFILM_FRAME_DIFFUSION))

/// The stages up to but not including grain, which is where the split schedule cuts.
#define FOTUFILM_AOT_HEAD ((FOTUFILM_AOT_ALL_STAGES & ~(FOTUFILM_FRAME_GRAIN | FOTUFILM_FRAME_PRINT_MTF)))

/// Grain and the enlarger: the half of develop that runs after the cut.
#define FOTUFILM_AOT_TAIL ((FOTUFILM_FRAME_GRAIN | FOTUFILM_FRAME_PRINT_MTF | FOTUFILM_FRAME_DENSITY_IN))

/// `PipelineStage.negative`: every stage up to and including grain, and nothing that images the
/// negative afterwards. The same cut the hybrid still renderer makes, moved past grain so that what
/// crosses the boundary is a developed negative rather than a latent one.
#define FOTUFILM_AOT_NEGATIVE_SPAN (((FOTUFILM_AOT_ALL_STAGES & ~FOTUFILM_FRAME_PRINT_MTF) | FOTUFILM_FRAME_DENSITY_OUT))

/// `PipelineStage.print`: the enlarger and the print medium, reading densities. Everything the
/// negative span already ran is absent, which is what makes the two spans together run each stage
/// exactly once.
#define FOTUFILM_AOT_PRINT_SPAN ((FOTUFILM_FRAME_PRINT_MTF | FOTUFILM_FRAME_DENSITY_IN))

/// `PipelineStage.texture`: the same stages the negative span runs, differenced against a
/// development with none of them. The enlarger is in, because it is one of the selectable spatial
/// stages here rather than the print it belongs to in a full render.
#define FOTUFILM_AOT_TEXTURE_SPAN ((FOTUFILM_AOT_ALL_STAGES | FOTUFILM_FRAME_TEXTURE))

/// Texture span for an empty spatial selection. It requires an exact variant because unused near-
/// identity stages would enter only one side of the density difference. Pointwise glare and coupler
/// inhibition remain on both sides and cancel.
#define FOTUFILM_AOT_TEXTURE_FLAT_SPAN ((FOTUFILM_FRAME_FLARE | FOTUFILM_FRAME_COUPLERS | FOTUFILM_FRAME_TEXTURE))

/// A colour negative: DIR couplers that diffuse, and no luminance MTF arm. This is a stock that
/// gets printed, not the light-box view of one — that borrows the reversal flag instead.
#define FOTUFILM_AOT_NEGATIVE ((FOTUFILM_FRAME_MTF | FOTUFILM_FRAME_HALATION | FOTUFILM_FRAME_COUPLERS | FOTUFILM_FRAME_COUPLER_DIFFUSION | FOTUFILM_FRAME_ADJACENCY | FOTUFILM_FRAME_GRAIN))

/// A transparency or a black-and-white stock without an interimage correction.
#define FOTUFILM_AOT_SLIDE ((FOTUFILM_FRAME_MTF | FOTUFILM_FRAME_HALATION | FOTUFILM_FRAME_ADJACENCY | FOTUFILM_FRAME_GRAIN))

/// A transparency whose development carries a pointwise interimage correction.
#define FOTUFILM_AOT_SLIDE_INTERIMAGE ((FOTUFILM_AOT_SLIDE | FOTUFILM_FRAME_COUPLERS))

/// The same without the emulsion MTF, which is compiled out when the stock's diffusion does not
/// reach a pixel at the frame's size.
#define FOTUFILM_AOT_SLIDE_NO_MTF ((FOTUFILM_AOT_SLIDE & ~FOTUFILM_FRAME_MTF))

/// Every stage a class can carry. One variant per exact class compiles all of them and the request
/// selects at run time: a stage the frame does not ask for is bypassed, not run at zero strength,
/// so the served frame is the requested frame.
#define FOTUFILM_AOT_FULL_STAGES ((FOTUFILM_AOT_ALL_STAGES | FOTUFILM_FRAME_FLARE | FOTUFILM_FRAME_GRAIN_MOTTLE | FOTUFILM_FRAME_DONOR_LAYER))

/// Common float video graphs. AOT windowed twins keep the same arguments and physics, with their
/// intermediate rows stored in bounded circular buffers; the shim picks one only for a request
/// inside this stage set.
#define FOTUFILM_AOT_BASIC_STAGES (((FOTUFILM_AOT_ALL_STAGES & ~(FOTUFILM_FRAME_MTF_LUMA | FOTUFILM_FRAME_DIFFUSION)) | FOTUFILM_FRAME_FLOAT_IO | FOTUFILM_FRAME_REALTIME))

/// The disc grain model, the one stage that is expensive to compile rather than to skip. A still
/// class carries it as a twin; a realtime class never develops discs, so its one variant carries
/// the bit for coverage at no cost.
#define FOTUFILM_AOT_DISC(mask) ((mask) | FOTUFILM_FRAME_DISC_GRAIN)

#define FOTUFILM_AOT_VARIANTS(X) \
    /* The byte-input classes are realtime by construction: half-precision stores, the extern \
       Metal blurs, and no disc model. */ \
    X(color, FOTUFILM_AOT_FULL_STAGES | FOTUFILM_FRAME_DISC_GRAIN) \
    X(monochrome, FOTUFILM_AOT_FULL_STAGES | FOTUFILM_FRAME_DISC_GRAIN | FOTUFILM_FRAME_MONOCHROME) \
    /* The split recording road: the head develops to a density seam, the tail images it. See \
       FOTUFILM_AOT_HEAD and FOTUFILM_AOT_TAIL for the stages each half runs. */ \
    X(color_head, FOTUFILM_AOT_FULL_STAGES | FOTUFILM_FRAME_DISC_GRAIN | FOTUFILM_FRAME_DENSITY_OUT) \
    X(monochrome_head, FOTUFILM_AOT_FULL_STAGES | FOTUFILM_FRAME_DISC_GRAIN | FOTUFILM_FRAME_MONOCHROME | FOTUFILM_FRAME_DENSITY_OUT) \
    X(color_tail, FOTUFILM_AOT_FULL_STAGES | FOTUFILM_FRAME_DISC_GRAIN | FOTUFILM_FRAME_DENSITY_IN) \
    X(monochrome_tail, FOTUFILM_AOT_FULL_STAGES | FOTUFILM_FRAME_DISC_GRAIN | FOTUFILM_FRAME_MONOCHROME | FOTUFILM_FRAME_DENSITY_IN) \
    /* Deep video: float I/O on the realtime schedule, which keeps full-precision stores. The \
       delivery encode and its transfer are chosen by the request, not the variant. */ \
    X(color_float_realtime, FOTUFILM_AOT_FULL_STAGES | FOTUFILM_FRAME_DISC_GRAIN | FOTUFILM_FRAME_FLOAT_IO | FOTUFILM_FRAME_REALTIME) \
    X(monochrome_float_realtime, FOTUFILM_AOT_FULL_STAGES | FOTUFILM_FRAME_DISC_GRAIN | FOTUFILM_FRAME_MONOCHROME | FOTUFILM_FRAME_FLOAT_IO | FOTUFILM_FRAME_REALTIME) \
    X(color_float_realtime_measure, FOTUFILM_AOT_FULL_STAGES | FOTUFILM_FRAME_DISC_GRAIN | FOTUFILM_FRAME_FLOAT_IO | FOTUFILM_FRAME_REALTIME | FOTUFILM_FRAME_FLARE_MEASURE) \
    X(monochrome_float_realtime_measure, FOTUFILM_AOT_FULL_STAGES | FOTUFILM_FRAME_DISC_GRAIN | FOTUFILM_FRAME_MONOCHROME | FOTUFILM_FRAME_FLOAT_IO | FOTUFILM_FRAME_REALTIME | FOTUFILM_FRAME_FLARE_MEASURE) \
    X(color_float_realtime_texture, FOTUFILM_AOT_FULL_STAGES | FOTUFILM_FRAME_DISC_GRAIN | FOTUFILM_FRAME_FLOAT_IO | FOTUFILM_FRAME_REALTIME | FOTUFILM_FRAME_TEXTURE) \
    X(monochrome_float_realtime_texture, FOTUFILM_AOT_FULL_STAGES | FOTUFILM_FRAME_DISC_GRAIN | FOTUFILM_FRAME_MONOCHROME | FOTUFILM_FRAME_FLOAT_IO | FOTUFILM_FRAME_REALTIME | FOTUFILM_FRAME_TEXTURE) \
    X(color_float_realtime_negative, FOTUFILM_AOT_FULL_STAGES | FOTUFILM_FRAME_DISC_GRAIN | FOTUFILM_FRAME_FLOAT_IO | FOTUFILM_FRAME_REALTIME | FOTUFILM_FRAME_DENSITY_OUT) \
    X(monochrome_float_realtime_negative, FOTUFILM_AOT_FULL_STAGES | FOTUFILM_FRAME_DISC_GRAIN | FOTUFILM_FRAME_MONOCHROME | FOTUFILM_FRAME_FLOAT_IO | FOTUFILM_FRAME_REALTIME | FOTUFILM_FRAME_DENSITY_OUT) \
    X(color_float_realtime_print, FOTUFILM_AOT_FULL_STAGES | FOTUFILM_FRAME_DISC_GRAIN | FOTUFILM_FRAME_FLOAT_IO | FOTUFILM_FRAME_REALTIME | FOTUFILM_FRAME_DENSITY_IN) \
    X(monochrome_float_realtime_print, FOTUFILM_AOT_FULL_STAGES | FOTUFILM_FRAME_DISC_GRAIN | FOTUFILM_FRAME_MONOCHROME | FOTUFILM_FRAME_FLOAT_IO | FOTUFILM_FRAME_REALTIME | FOTUFILM_FRAME_DENSITY_IN) \
    /* The float still classes: the reference schedule, with the disc grain model as a twin. */ \
    X(color_float, FOTUFILM_AOT_FULL_STAGES | FOTUFILM_FRAME_FLOAT_IO) \
    X(color_float_disc, FOTUFILM_AOT_DISC(FOTUFILM_AOT_FULL_STAGES | FOTUFILM_FRAME_FLOAT_IO)) \
    X(monochrome_float, FOTUFILM_AOT_FULL_STAGES | FOTUFILM_FRAME_MONOCHROME | FOTUFILM_FRAME_FLOAT_IO) \
    X(monochrome_float_disc, FOTUFILM_AOT_DISC(FOTUFILM_AOT_FULL_STAGES | FOTUFILM_FRAME_MONOCHROME | FOTUFILM_FRAME_FLOAT_IO)) \
    X(color_float_exact, FOTUFILM_AOT_FULL_STAGES | FOTUFILM_FRAME_FLOAT_IO | FOTUFILM_FRAME_EXACT_MATH) \
    X(color_float_exact_disc, FOTUFILM_AOT_DISC(FOTUFILM_AOT_FULL_STAGES | FOTUFILM_FRAME_FLOAT_IO | FOTUFILM_FRAME_EXACT_MATH)) \
    X(monochrome_float_exact, FOTUFILM_AOT_FULL_STAGES | FOTUFILM_FRAME_MONOCHROME | FOTUFILM_FRAME_FLOAT_IO | FOTUFILM_FRAME_EXACT_MATH) \
    X(monochrome_float_exact_disc, FOTUFILM_AOT_DISC(FOTUFILM_AOT_FULL_STAGES | FOTUFILM_FRAME_MONOCHROME | FOTUFILM_FRAME_FLOAT_IO | FOTUFILM_FRAME_EXACT_MATH)) \
    X(color_float_measure, FOTUFILM_AOT_FULL_STAGES | FOTUFILM_FRAME_FLOAT_IO | FOTUFILM_FRAME_FLARE_MEASURE) \
    X(color_float_measure_disc, FOTUFILM_AOT_DISC(FOTUFILM_AOT_FULL_STAGES | FOTUFILM_FRAME_FLOAT_IO | FOTUFILM_FRAME_FLARE_MEASURE)) \
    X(monochrome_float_measure, FOTUFILM_AOT_FULL_STAGES | FOTUFILM_FRAME_MONOCHROME | FOTUFILM_FRAME_FLOAT_IO | FOTUFILM_FRAME_FLARE_MEASURE) \
    X(monochrome_float_measure_disc, FOTUFILM_AOT_DISC(FOTUFILM_AOT_FULL_STAGES | FOTUFILM_FRAME_MONOCHROME | FOTUFILM_FRAME_FLOAT_IO | FOTUFILM_FRAME_FLARE_MEASURE)) \
    /* An empty spatial selection is served here too: a bypassed stage is an identity on both \
       sides of the density difference. */ \
    X(color_float_texture, FOTUFILM_AOT_FULL_STAGES | FOTUFILM_FRAME_FLOAT_IO | FOTUFILM_FRAME_TEXTURE) \
    X(color_float_texture_disc, FOTUFILM_AOT_DISC(FOTUFILM_AOT_FULL_STAGES | FOTUFILM_FRAME_FLOAT_IO | FOTUFILM_FRAME_TEXTURE)) \
    X(monochrome_float_texture, FOTUFILM_AOT_FULL_STAGES | FOTUFILM_FRAME_MONOCHROME | FOTUFILM_FRAME_FLOAT_IO | FOTUFILM_FRAME_TEXTURE) \
    X(monochrome_float_texture_disc, FOTUFILM_AOT_DISC(FOTUFILM_AOT_FULL_STAGES | FOTUFILM_FRAME_MONOCHROME | FOTUFILM_FRAME_FLOAT_IO | FOTUFILM_FRAME_TEXTURE)) \
    X(color_float_negative, FOTUFILM_AOT_FULL_STAGES | FOTUFILM_FRAME_FLOAT_IO | FOTUFILM_FRAME_DENSITY_OUT) \
    X(color_float_negative_disc, FOTUFILM_AOT_DISC(FOTUFILM_AOT_FULL_STAGES | FOTUFILM_FRAME_FLOAT_IO | FOTUFILM_FRAME_DENSITY_OUT)) \
    X(monochrome_float_negative, FOTUFILM_AOT_FULL_STAGES | FOTUFILM_FRAME_MONOCHROME | FOTUFILM_FRAME_FLOAT_IO | FOTUFILM_FRAME_DENSITY_OUT) \
    X(monochrome_float_negative_disc, FOTUFILM_AOT_DISC(FOTUFILM_AOT_FULL_STAGES | FOTUFILM_FRAME_MONOCHROME | FOTUFILM_FRAME_FLOAT_IO | FOTUFILM_FRAME_DENSITY_OUT)) \
    X(color_float_print, FOTUFILM_AOT_FULL_STAGES | FOTUFILM_FRAME_FLOAT_IO | FOTUFILM_FRAME_DENSITY_IN) \
    X(color_float_print_disc, FOTUFILM_AOT_DISC(FOTUFILM_AOT_FULL_STAGES | FOTUFILM_FRAME_FLOAT_IO | FOTUFILM_FRAME_DENSITY_IN)) \
    X(monochrome_float_print, FOTUFILM_AOT_FULL_STAGES | FOTUFILM_FRAME_MONOCHROME | FOTUFILM_FRAME_FLOAT_IO | FOTUFILM_FRAME_DENSITY_IN) \
    X(monochrome_float_print_disc, FOTUFILM_AOT_DISC(FOTUFILM_AOT_FULL_STAGES | FOTUFILM_FRAME_MONOCHROME | FOTUFILM_FRAME_FLOAT_IO | FOTUFILM_FRAME_DENSITY_IN)) \
    /* The two halves of the two-pass striped render; see FOTUFILM_FRAME_LIGHT_OUT and \
       FOTUFILM_FRAME_FIELDS_IN. */ \
    X(color_float_fields, FOTUFILM_AOT_FULL_STAGES | FOTUFILM_FRAME_FLOAT_IO | FOTUFILM_FRAME_FIELDS_IN) \
    X(color_float_fields_disc, FOTUFILM_AOT_DISC(FOTUFILM_AOT_FULL_STAGES | FOTUFILM_FRAME_FLOAT_IO | FOTUFILM_FRAME_FIELDS_IN)) \
    X(monochrome_float_fields, FOTUFILM_AOT_FULL_STAGES | FOTUFILM_FRAME_MONOCHROME | FOTUFILM_FRAME_FLOAT_IO | FOTUFILM_FRAME_FIELDS_IN) \
    X(monochrome_float_fields_disc, FOTUFILM_AOT_DISC(FOTUFILM_AOT_FULL_STAGES | FOTUFILM_FRAME_MONOCHROME | FOTUFILM_FRAME_FLOAT_IO | FOTUFILM_FRAME_FIELDS_IN)) \
    /* Nothing past the light is compiled, so the grain bits cost nothing and cover any request. */ \
    X(color_float_light, FOTUFILM_AOT_FULL_STAGES | FOTUFILM_FRAME_DISC_GRAIN | FOTUFILM_FRAME_FLOAT_IO | FOTUFILM_FRAME_LIGHT_OUT) \
    X(monochrome_float_light, FOTUFILM_AOT_FULL_STAGES | FOTUFILM_FRAME_DISC_GRAIN | FOTUFILM_FRAME_MONOCHROME | FOTUFILM_FRAME_FLOAT_IO | FOTUFILM_FRAME_LIGHT_OUT) \
    /* No film in the gate: `PlainDevelop` as a kernel. Its own class rather than a corner of the \
       others, because FOTUFILM_FRAME_NO_FILM is an exact bit — a variant that develops film is \
       not a richer version of one that develops none, it is a different picture — so a request \
       for it can be served by nothing else. */ \
    X(no_film_float, FOTUFILM_FRAME_FLOAT_IO | FOTUFILM_FRAME_NO_FILM) \
    X(no_film_float_exact, FOTUFILM_FRAME_FLOAT_IO | FOTUFILM_FRAME_EXACT_MATH | FOTUFILM_FRAME_NO_FILM)

/// Compiled a second time with the folded row-window schedule, for the hosts that cannot hold a
/// whole frame's intermediates. The shim picks a twin only when the request's stages fit
/// BASIC_STAGES, whose reach it can bound.
#define FOTUFILM_AOT_WINDOWED_VARIANTS(X) \
    X(color_float_realtime, FOTUFILM_AOT_BASIC_STAGES) \
    X(monochrome_float_realtime, FOTUFILM_AOT_BASIC_STAGES | FOTUFILM_FRAME_MONOCHROME)

/// A stage bit is covered by any variant that carries it; an exact bit must match. The delivery
/// encode and its transfer (ENCODE_OUT, OUTPUT_*) are neither: the pipeline chooses them at run
/// time.
#define FOTUFILM_VARIANT_STAGE_BITS \
    (FOTUFILM_AOT_ALL_STAGES | FOTUFILM_FRAME_GRAIN_MOTTLE | FOTUFILM_FRAME_FLARE | FOTUFILM_FRAME_DISC_GRAIN | FOTUFILM_FRAME_DONOR_LAYER)
#define FOTUFILM_VARIANT_EXACT_BITS \
    (FOTUFILM_FRAME_MONOCHROME | FOTUFILM_FRAME_FLOAT_IO | FOTUFILM_FRAME_REALTIME | FOTUFILM_FRAME_EXACT_MATH | FOTUFILM_FRAME_DENSITY_OUT | FOTUFILM_FRAME_DENSITY_IN | FOTUFILM_FRAME_FLARE_MEASURE | FOTUFILM_FRAME_LIGHT_OUT | FOTUFILM_FRAME_FIELDS_IN | FOTUFILM_FRAME_TEXTURE | FOTUFILM_FRAME_NO_FILM)
#define FOTUFILM_AOT_VARIANT_BITS (FOTUFILM_VARIANT_STAGE_BITS | FOTUFILM_VARIANT_EXACT_BITS)

#endif
