// Generated by tools/calibration/crystalarchive/extract_paper.py.
// Source curves and extraction evidence live under research/spectral.

import Foundation

/// The Fujicolor RA-4 paper, digitised from FUJICOLOR CRYSTAL ARCHIVE
/// PAPER Type CA, Fujifilm publication AF3-0250U2 (November 2018), on
/// the 380...780 nm grid at 5 nm steps.
///
/// The pack's Fujicolor negatives were designed to be printed on this
/// rather than on the Kodak sheet in `PrintPaperSpectra`, and the two
/// are not small variations on each other: this paper's
/// green-sensitive layer peaks at 550 nm against Ektacolor Edge's 545
/// and carries a second lobe in the blue that the Kodak record has no
/// trace of, because a paper meant for a laser printer is sensitised
/// to the lines it will be exposed by.
enum CrystalArchivePaperSpectra {
    /// Spectral reflection density of the developed cyan, magenta
    /// and yellow dyes, from the sheet's section 12. Each record is
    /// drawn to a peak of 1.0 and the sheet says nothing about what
    /// ratio of the three forms a neutral — its only caption is the
    /// process — so, as with E-7020, that scaling states three
    /// shapes and not the ratio between them: `neutralAmounts`
    /// carries the ratio and `SpectralGrid.crystalArchiveDyes`
    /// applies it. Outside the printed 400...750 nm span each
    /// record holds its end value.
    static let dyeDensity: [[Float]] = [
        [
            0.19220546, 0.19220546, 0.19220546, 0.19220546, 0.19365342, 0.16436273, 0.1443334,
            0.13144533, 0.11274986, 0.094785481, 0.079645367, 0.067401537, 0.056925454, 0.049610301,
            0.043031282, 0.039123945, 0.03557072, 0.033653555, 0.033163451, 0.033306106, 0.03523982,
            0.037804711, 0.041692549, 0.045842064, 0.052958632, 0.060897369, 0.06941359, 0.080952559,
            0.093462478, 0.10633466, 0.1230526, 0.14410619, 0.16714558, 0.19425743, 0.22615088,
            0.26073846, 0.29811903, 0.33837222, 0.38078419, 0.42864845, 0.48071009, 0.54111708,
            0.60807363, 0.68114145, 0.75384994, 0.8216359, 0.87890162, 0.91754612, 0.94436889,
            0.95814558, 0.9686973, 0.98019231, 0.99028469, 0.99773285, 0.99959341, 0.99121715,
            0.97104318, 0.93525018, 0.89093738, 0.83297188, 0.76840007, 0.6995561, 0.63102427,
            0.56516818, 0.50380743, 0.44840676, 0.39790332, 0.35352757, 0.31257422, 0.27524259,
            0.24047827, 0.20906342, 0.18006068, 0.15406523, 0.13459145, 0.13292653, 0.13292653,
            0.13292653, 0.13292653, 0.13292653, 0.13292653,
        ],
        [
            0.23132705, 0.23132705, 0.23132705, 0.23132705, 0.23001373, 0.20116893, 0.17571296,
            0.15454988, 0.13568241, 0.12325247, 0.12179563, 0.12659792, 0.13544703, 0.14832559,
            0.16351209, 0.18308538, 0.2063725, 0.23493788, 0.26729037, 0.30652397, 0.35197497,
            0.4018107, 0.45516699, 0.51886742, 0.58588124, 0.65625893, 0.72607328, 0.7899995,
            0.84295355, 0.88478909, 0.92027834, 0.94843328, 0.97285572, 0.99251058, 1.0008357,
            0.99112672, 0.95933108, 0.90571503, 0.82622496, 0.73349761, 0.63204938, 0.5005638,
            0.44025576, 0.35924206, 0.29440669, 0.24001783, 0.19805262, 0.16383621, 0.13552876,
            0.11311277, 0.095604286, 0.080463936, 0.069086849, 0.060653177, 0.054098965, 0.047618831,
            0.042225194, 0.037375406, 0.033358524, 0.029452055, 0.025168081, 0.021385791, 0.017383268,
            0.014203145, 0.011778268, 0.0093350325, 0.0080677481, 0.0064224516, 0.0062101009, 0.0059310148,
            0.0055355345, 0.0049419346, 0.004709364, 0.0046799252, 0.0046875, 0.0046875, 0.0046875,
            0.0046875, 0.0046875, 0.0046875, 0.0046875,
        ],
        [
            0.70329392, 0.70329392, 0.70329392, 0.70329392, 0.70235308, 0.7131886, 0.74458724,
            0.78836057, 0.84278476, 0.89325231, 0.93749196, 0.96873144, 0.9899762, 0.99981521,
            0.9973076, 0.97902627, 0.94287523, 0.88739114, 0.81482469, 0.73455559, 0.64825207,
            0.56380017, 0.50201755, 0.41362613, 0.34876567, 0.29541031, 0.24858918, 0.20980097,
            0.1768328, 0.15156925, 0.13713101, 0.11246277, 0.10100159, 0.090515171, 0.08269196,
            0.076794528, 0.071771449, 0.06709386, 0.063673881, 0.059934122, 0.056691695, 0.054942233,
            0.05127905, 0.047934234, 0.045556451, 0.043817367, 0.04213816, 0.041360923, 0.039629889,
            0.038909915, 0.03764016, 0.03590986, 0.034390394, 0.032278503, 0.029106071, 0.026173532,
            0.022114794, 0.018902151, 0.014335115, 0.0125, 0.0125, 0.0125, 0.0125,
            0.0125, 0.0125, 0.0125, 0.0125, 0.0125, 0.0125, 0.0125,
            0.0125, 0.0125, 0.0125, 0.0125, 0.0125, 0.0125, 0.0125,
            0.0125, 0.0125, 0.0125, 0.0125,
        ],
    ]

    /// The amounts of the three dyes that form a visual neutral of density
    /// 1.0 — what E-55, E-4000 and H-1-2383 state in their captions and
    /// AF3-0250U2 does not, solved from the shapes above by
    /// `tools/calibration/neutral_amounts.py`.
    ///
    /// Without them the partition would divide three peak-normalised curves
    /// by their sum, which asserts that equal peak densities form a neutral.
    /// This sheet's dyes do not: they want 0.934 of the cyan's amount
    /// in magenta and 1.002 in yellow, and the difference is how much
    /// of each dye's unwanted absorption a printed colour carries.
    ///
    /// The solve needs a light and an observer. Both are CIE D65 and
    /// the CIE 1931 2-degree observer, because that is the pair
    /// `SpectralGrid.toLinearDisplayP3` views every finished print through:
    /// a neutral solved under any other light is one the renderer would
    /// then decline to agree with.
    static let neutralAmounts: [Float] = [0.89341696, 0.83406183, 0.8952373]

    /// Relative sensitivity of the cyan-, magenta- and
    /// yellow-forming layers, from the sheet's section 13, on the
    /// publication's own linear scale. Zero outside each record's
    /// printed span, which is where `SpectralGrid.continuedTails`
    /// takes over — and it takes over earlier here than on a log
    /// plot, because a linear axis stops showing a record once it
    /// falls under a twentieth of its peak, which is well before the
    /// paper stops responding.
    static let layerSensitivity: [[Float]] = [
        [
            0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0,
            0, 0, 0.067509721, 0.081940105, 0.1047803, 0.13923561, 0.18875664,
            0.23969207, 0.29421824, 0.33754413, 0.37595307, 0.41074785, 0.44376663, 0.46836426,
            0.48794837, 0.50322008, 0.51472208, 0.5284521, 0.54160323, 0.55311515, 0.57210088,
            0.58334368, 0.55341416, 0.45394551, 0.29513201, 0.23084304, 0.18614306, 0.13261111,
            0.069976364, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0,
        ],
        [
            0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0.16156947, 0.17655042, 0.18903217, 0.20048398,
            0.21011306, 0.21863697, 0.2270082, 0.2372562, 0.24996858, 0.2651856, 0.28088022,
            0.29896359, 0.33281618, 0.38335837, 0.43632655, 0.48884771, 0.52409485, 0.54293454,
            0.55002145, 0.55755998, 0.60287855, 0.7172259, 0.88065539, 0.97207925, 1.0596311,
            0.99409124, 0.86569914, 0.6825717, 0.55878138, 0.44005451, 0.29125035, 0.17590552,
            0.094354942, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0,
        ],
        [
            0, 0, 0, 0, 0, 0.40970206, 0.46543291,
            0.50511595, 0.5238452, 0.53431366, 0.54405814, 0.5526905, 0.561168, 0.57050698,
            0.57914088, 0.60999489, 0.66275738, 0.71672309, 0.82235874, 0.9615565, 1.0871161,
            1.1791043, 1.1418496, 0.89476486, 0.70311778, 0.57016622, 0.43932669, 0.33671091,
            0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0,
        ],
    ]
}
