// Generated by tools/calibration/h12393/extract_paper.py.
// Source curves and extraction evidence live under research/spectral.

import Foundation

/// The higher-contrast release print, read from KODAK VISION Premier
/// Color Print Film 2393's own curve sheets on the 380...780 nm grid
/// at 5 nm steps.
///
/// The second projected medium here. It shares 2383's process and its
/// xenon viewing lamp, and differs in the print itself: Premier is the
/// stock a release was timed onto when the release wanted more
/// contrast and a deeper black than 2383 gives.
///
/// Kodak drew these three plots as vector artwork rather than the
/// embedded rasters H-1-2383 carries, so the numbers below are the
/// publisher's own bezier control points evaluated, with no tracing
/// step and no rasterisation between the drawing and the table.
enum Vision2393PrintSpectra {
    /// Diffuse spectral density of the developed cyan, magenta and
    /// yellow dyes, from the sheet's SPECTRAL DYE DENSITY CURVES.
    ///
    /// Drawn, like 2383's and unlike the two RA-4 papers', at the
    /// amounts that form a visual density of 1.0 under a xenon-arc
    /// viewing illuminant — the plot's own caption — so dividing
    /// them by their pointwise sum in `SpectralGrid.partition` is a
    /// reading rather than a convention. The sheet draws that
    /// neutral as a fourth curve and it was held out of the
    /// calibration: solving it afterwards returns 1.01, 1.01 and
    /// 1.07 of the three plus a base of 0.065 D, at 0.0148 D RMS
    /// and 0.0485 D at worst over 400...780 nm.
    ///
    /// Each record holds its end value outside the 300...750 nm the
    /// sheet draws it over.
    static let dyeDensity: [[Float]] = [
        [
            0.29308997, 0.30068066, 0.30738165, 0.30779601, 0.3026141, 0.28723978, 0.26431997,
            0.23780286, 0.20793395, 0.17776006, 0.15092314, 0.12883953, 0.10878543, 0.090535462,
            0.075000258, 0.062229429, 0.051372646, 0.042405519, 0.035567996, 0.031192272, 0.027935959,
            0.025597627, 0.024446561, 0.024761351, 0.026729906, 0.030324323, 0.035244934, 0.04112114,
            0.04886828, 0.059055954, 0.071854923, 0.08726469, 0.10502592, 0.12460041, 0.14585987,
            0.17006606, 0.19791451, 0.2301937, 0.2677664, 0.31129473, 0.3606886, 0.41453698,
            0.47167542, 0.53126573, 0.5922222, 0.65332453, 0.7133444, 0.77280352, 0.83243926,
            0.88709996, 0.93418722, 0.9738816, 1.0074095, 1.0356071, 1.0579988, 1.0745211,
            1.0849538, 1.0889344, 1.0861076, 1.0781623, 1.0646226, 1.0436964, 1.0136485,
            0.97472222, 0.93313287, 0.88609668, 0.82851813, 0.77841061, 0.72068909, 0.66206052,
            0.60376768, 0.54516225, 0.48127089, 0.41654947, 0.36587765, 0.34271324, 0.34271324,
            0.34271324, 0.34271324, 0.34271324, 0.34271324,
        ],
        [
            0.041843134, 0.041215623, 0.041858517, 0.044589821, 0.049287843, 0.055098491, 0.062064207,
            0.07022671, 0.079376796, 0.085575934, 0.088230632, 0.087539831, 0.082915801, 0.075668006,
            0.075340357, 0.087986337, 0.099549792, 0.11710165, 0.14797567, 0.19221047, 0.23562445,
            0.28534707, 0.3419958, 0.40407708, 0.468418, 0.55122997, 0.6345973, 0.69205356,
            0.73412495, 0.77679887, 0.81341181, 0.84128397, 0.8634677, 0.87528399, 0.86550098,
            0.83655309, 0.79080194, 0.72715029, 0.66269356, 0.57910336, 0.50068402, 0.4069544,
            0.33017016, 0.27104108, 0.22398372, 0.18346678, 0.15061673, 0.12512273, 0.10506654,
            0.088712541, 0.075416349, 0.064578548, 0.055492336, 0.047488156, 0.040160129, 0.035689683,
            0.032907413, 0.030419729, 0.026633929, 0.021264008, 0.016408681, 0.01382493, 0.013051692,
            0.013385068, 0.01421739, 0.014951158, 0.014985058, 0.013775082, 0.012751696, 0.011808937,
            0.010892578, 0.0099940088, 0.0091115925, 0.0082481269, 0.007417228, 0.0069341081, 0.0069341081,
            0.0069341081, 0.0069341081, 0.0069341081, 0.0069341081,
        ],
        [
            0.22015997, 0.24290159, 0.28686676, 0.33908607, 0.39269398, 0.4565145, 0.52812615,
            0.59212655, 0.64520312, 0.6974559, 0.73496711, 0.75788298, 0.77074439, 0.7767539,
            0.77736403, 0.77173524, 0.75856863, 0.736043, 0.70182957, 0.65298246, 0.58717005,
            0.50730776, 0.43059013, 0.37669504, 0.31948265, 0.25827871, 0.190179, 0.14864788,
            0.11939704, 0.094201611, 0.074142936, 0.05958296, 0.050464528, 0.044322481, 0.037872252,
            0.031430469, 0.025797206, 0.021775864, 0.019422615, 0.018112729, 0.017006667, 0.016044598,
            0.01521483, 0.014508504, 0.013915498, 0.013425426, 0.013029722, 0.012717398, 0.012479196,
            0.012305518, 0.012186237, 0.012112178, 0.012073389, 0.012060268, 0.012063423, 0.012073129,
            0.01207994, 0.012026884, 0.011828367, 0.011491865, 0.011029576, 0.010455939, 0.0097872949,
            0.0090417071, 0.0082400649, 0.0074034666, 0.0065543272, 0.0057151333, 0.0049084783, 0.0041554252,
            0.0034764099, 0.0028902766, 0.0024130376, 0.0020591392, 0.0018407978, 0.0017880677, 0.0017880677,
            0.0017880677, 0.0017880677, 0.0017880677, 0.0017880677,
        ],
    ]

    /// Spectral sensitivity of the cyan-, magenta- and
    /// yellow-forming layers, from the sheet's SPECTRAL SENSITIVITY
    /// CURVES, as linear sensitivity: the plot plots log sensitivity
    /// at a density of 1.0 above D-min, and these are 10 to that.
    ///
    /// Zero outside the span each record is drawn over, because a
    /// layer the sheet stops drawing is one the sheet declines to
    /// state rather than one that reads on.
    static let layerSensitivity: [[Float]] = [
        [
            0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0.0030809498, 0.0036979917,
            0.0039882685, 0.0044026802, 0.0050601757, 0.0060517565, 0.0074854501, 0.0094029361, 0.011653818,
            0.013865258, 0.015613531, 0.016744829, 0.017974331, 0.019534175, 0.021576871, 0.024359798,
            0.028346625, 0.034402561, 0.04417716, 0.060835497, 0.10625574, 0.13907252, 0.13716225,
            0.10204585, 0.068397777, 0.050585735, 0.031632709, 0.018481383, 0.007196063, 0.0022650384,
            0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0,
        ],
        [
            0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0.0062793301,
            0.012934301, 0.022811466, 0.028029714, 0.033558366, 0.040107052, 0.048914572, 0.062928623,
            0.082816853, 0.10408367, 0.12265551, 0.13450893, 0.13641755, 0.13381661, 0.13426961,
            0.13766699, 0.14751905, 0.17814567, 0.24448015, 0.38777614, 0.56535641, 0.58578455,
            0.32908195, 0.2029448, 0.10394982, 0.048225984, 0.019930539, 0.0077468627, 0.0032987091,
            0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0,
        ],
        [
            0.31882964, 0.30378908, 0.32780368, 0.3695727, 0.42730373, 0.50270333, 0.59941582,
            0.72304696, 0.88203588, 1.0919363, 1.3457119, 1.6101936, 1.9016906, 2.2664028,
            2.7132986, 3.3311741, 3.916198, 4.0828698, 2.8826352, 1.240487, 0.61573311,
            0.19864925, 0.064397348, 0.018138009, 0.0053542742, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0,
        ],
    ]

    /// The red record of the sheet's CHARACTERISTIC CURVES,
    /// fitted to the engine's softplus H&D family at RMS 0.0527 D
    /// (worst 0.1379 D), reaching 5.275 D.
    static let redCurve = CharacteristicCurve(
        dMin: 0.0715611, gamma: 6.10157, toe: 0.965955, toeWidth: 0.197075, shoulder: 1.81879, shoulderWidth: 0.144447)

    /// The green record of the sheet's CHARACTERISTIC CURVES,
    /// fitted to the engine's softplus H&D family at RMS 0.0261 D
    /// (worst 0.0554 D), reaching 5.555 D.
    static let greenCurve = CharacteristicCurve(
        dMin: 0.0672409, gamma: 8.80819, toe: 0.847133, toeWidth: 0.244557, shoulder: 1.47021, shoulderWidth: 0.206162)

    /// The blue record of the sheet's CHARACTERISTIC CURVES,
    /// fitted to the engine's softplus H&D family at RMS 0.0138 D
    /// (worst 0.0351 D), reaching 5.330 D.
    static let blueCurve = CharacteristicCurve(
        dMin: 0.128026, gamma: 6.61943, toe: 0.438969, toeWidth: 0.231422, shoulder: 1.22479, shoulderWidth: 0.111926)
}
