#!/usr/bin/env python3
"""Export public engine constants for the browser; --check detects ABI or observer drift."""
import json
from pathlib import Path
import re
import subprocess
import sys
import tempfile

root = Path(__file__).resolve().parents[1]
header = root / 'Sources/FotufilmHalide/include/FotufilmHalide.h'
names = list(dict.fromkeys(re.findall(r'^\s*(FOTUFILM_CONFIG_\w+)\s*(?:=|,)', header.read_text(), re.M)))
names += ['FOTUFILM_FRAME_CONFIGURATION_COUNT']
with tempfile.TemporaryDirectory() as temporary:
    source = Path(temporary) / 'constants.cpp'
    executable = Path(temporary) / 'constants'
    source.write_text('#include <stdio.h>\n#include "FotufilmHalide.h"\nint main() {\n' +
                      '\n'.join(f'printf("%d\\n", {name});' for name in names) + '\n}')
    subprocess.run(['c++', '-I', str(header.parent), str(source), '-o', str(executable)], check=True)
    values = map(int, subprocess.check_output([str(executable)], text=True).split())
    layout = dict(zip([name.removeprefix('FOTUFILM_CONFIG_') for name in names], values))
spectrum = (root / 'Sources/FotufilmCore/SpectralModel.swift').read_text()
observer = {}
for name in ['xBar', 'yBar', 'zBar']:
    match = re.search(r'static let ' + name + r': \[Float\] = \[([^]]+)\]', spectrum)
    observer[name] = [float(v.strip()) for v in match[1].split(',') if v.strip()]
result = '// Generated by tools/export-web-constants.py from the public engine.\n'
result += 'export const CONFIG = ' + json.dumps(layout, indent=2) + '\n'
result += 'export const OBSERVER = ' + json.dumps(observer) + '\n'
target = root / 'web/src/engine-constants.js'
if '--check' in sys.argv:
    if not target.exists() or target.read_text() != result:
        sys.exit('Browser constants are stale. Run python3 tools/export-web-constants.py.')
else:
    target.write_text(result)
