#!/usr/bin/env python3

import json
from pathlib import Path
import sys
import textwrap

ROOT = Path(__file__).resolve().parents[1]
SCHEMA = ROOT / "Sources/FotufilmHalide/config-layout.json"
LOCK = ROOT / "Sources/FotufilmHalide/config-layout.lock.json"
HEADER = ROOT / "Sources/FotufilmHalide/include/FotufilmConfigLayout.h"
PREFIX = "FOTUFILM_"


def evaluate(expression, constants):
    if isinstance(expression, int):
        return expression
    names = {name: value for name, value in constants.items()}
    try:
        return int(eval(expression, {"__builtins__": {}}, names))  # noqa: S307 - schema is ours
    except Exception as error:
        raise ValueError(f"Cannot evaluate {expression!r}: {error}") from error


def resolve(schema):
    constants = {}
    for name, entry in schema["constants"].items():
        constants[name] = evaluate(entry["value"], constants)
    fields = []
    offset = 0
    for field in schema["fields"]:
        count = evaluate(field["count"], constants)
        if count <= 0:
            raise ValueError(f"Field {field['name']} must hold at least one float")
        fields.append({"name": field["name"], "offset": offset, "count": count,
                       "expression": field["count"], "doc": field.get("doc", "")})
        offset += count
    return constants, fields, offset


def comment(text, indent="    "):
    if not text:
        return []
    return [f"{indent}/// {line}" for line in textwrap.wrap(text, width=96 - len(indent))]


def render(schema, constants, fields, total):
    lines = [
        "// Generated by tools/generate-config-layout.py from Sources/FotufilmHalide/config-layout.json.",
        "#ifndef FOTUFILM_CONFIG_LAYOUT_H",
        "#define FOTUFILM_CONFIG_LAYOUT_H",
        "",
        "enum {",
    ]
    for name, entry in schema["constants"].items():
        lines += comment(entry.get("doc", ""))
        value = entry["value"]
        shown = value if isinstance(value, int) else " ".join(
            PREFIX + token if token in constants else token for token in str(value).split())
        lines.append(f"    {PREFIX}{name} = {shown},")
    lines += ["};", "",
              "enum {"]
    for field in fields:
        lines += comment(field["doc"])
        lines.append(f"    {PREFIX}CONFIG_{field['name']} = {field['offset']},")
    lines += ["};", "",
              "enum {"]
    for field in fields:
        lines.append(f"    {PREFIX}CONFIG_{field['name']}_COUNT = {field['count']},")
    lines += ["};", "",
              f"enum {{ {PREFIX}FRAME_CONFIGURATION_COUNT = {total} }};",
              "", "#endif", ""]
    return "\n".join(lines)


def lock_record(fields, total):
    return {"schema": 1, "count": total,
            "fields": {field["name"]: {"offset": field["offset"], "count": field["count"]}
                       for field in fields}}


def check_lock(record, previous):
    problems = []
    for name, locked in previous["fields"].items():
        current = record["fields"].get(name)
        if current is None:
            problems.append(f"{name} was removed; shipped kernels still read it")
        elif current != locked:
            problems.append(f"{name} moved from {locked} to {current}")
    if record["count"] < previous["count"]:
        problems.append(f"the configuration shrank from {previous['count']} to {record['count']}")
    return problems


def main(argv):
    check = "--check" in argv
    update_lock = "--update-lock" in argv
    schema = json.loads(SCHEMA.read_text())
    constants, fields, total = resolve(schema)
    header = render(schema, constants, fields, total)
    record = lock_record(fields, total)
    previous = json.loads(LOCK.read_text()) if LOCK.exists() else None

    problems = check_lock(record, previous) if previous else []
    if problems and not update_lock:
        for problem in problems:
            print(f"config-layout: {problem}", file=sys.stderr)
        sys.exit("The packed configuration ABI moved. Append fields instead, or pass "
                 "--update-lock if the break is intended and every kernel will be regenerated.")

    if check:
        stale = []
        if not HEADER.exists() or HEADER.read_text() != header:
            stale.append(str(HEADER.relative_to(ROOT)))
        if previous is None or previous != record:
            stale.append(str(LOCK.relative_to(ROOT)))
        if stale:
            sys.exit("Stale: " + ", ".join(stale)
                     + ". Run python3 tools/generate-config-layout.py.")
        print(f"config-layout: {len(fields)} fields, {total} floats, header and lock current")
        return
    HEADER.write_text(header)
    LOCK.write_text(json.dumps(record, indent=2) + "\n")
    print(f"config-layout: wrote {HEADER.relative_to(ROOT)} ({len(fields)} fields, {total} floats)")


if __name__ == "__main__":
    main(sys.argv[1:])
