#!/usr/bin/env python3
"""Synthetic decoder fixtures; requires numpy, tifffile and imagecodecs in a test environment."""
from pathlib import Path
import json
import numpy as np
import tifffile
root = Path(__file__).resolve().parents[1]
out = root / 'build/tiff-fixtures'
out.mkdir(parents=True, exist_ok=True)
# Source ICC generated by the web's own profile resource, never a private photograph.
import subprocess
subprocess.run(['node', '--input-type=module', '-e',
    "import{iccProfile}from './web/src/color-profiles.js';import{writeFileSync}from'node:fs';writeFileSync('build/tiff-fixtures/p3.icc',iccProfile('display-p3'));"], cwd=root, check=True)
profile=(out/'p3.icc').read_bytes()
y,x=np.mgrid[:45,:70]
rgb=np.stack([10000+x*600, 13000+y*900, 14000+(x+y)*200],axis=-1).astype(np.uint16)
cases=[]
def save(name,data,**kwargs):
    tifffile.imwrite(out/(name+'.tiff'),data,metadata=None,**kwargs)
    cases.append(name)
for compression in [None,'deflate','lzw','packbits']:
    save('rgb16-'+str(compression),rgb,photometric='rgb',rowsperstrip=7,compression=compression,iccprofile=profile)
save('rgb16-big',rgb,photometric='rgb',rowsperstrip=7,compression='deflate',predictor=True,byteorder='>',iccprofile=profile)
save('rgb16-planar',rgb.transpose(2,0,1),photometric='rgb',planarconfig='separate',rowsperstrip=7,compression='lzw',iccprofile=profile)
save('rgb16-tiled',rgb,photometric='rgb',tile=(16,16),compression='deflate',predictor=True,iccprofile=profile)
save('rgb16-planar-tiled',rgb.transpose(2,0,1),photometric='rgb',planarconfig='separate',tile=(16,16),compression='deflate',iccprofile=profile)
save('rgb16-bigtiff',rgb,photometric='rgb',bigtiff=True,iccprofile=profile)
for orientation in range(1,9):
    save('orientation-'+str(orientation),rgb,photometric='rgb',iccprofile=profile,extratags=[(274,'H',1,orientation,False)])
gray=np.arange(512,dtype=np.uint16)[None,:]*100+2000
gray=np.repeat(gray,8,axis=0)
save('gray16-black',gray,photometric='minisblack',rowsperstrip=3,compression='deflate')
save('gray16-white',65535-gray,photometric='miniswhite',rowsperstrip=3,compression='lzw')
alpha=np.full((45,70,1),32768,np.uint16)
save('rgba16-straight',np.concatenate([rgb,alpha],axis=-1),photometric='rgb',extrasamples='unassalpha',iccprofile=profile)
save('rgba16-associated',np.concatenate([(rgb.astype(np.float64)*32768/65535).round().astype(np.uint16),alpha],axis=-1),photometric='rgb',extrasamples='assocalpha',iccprofile=profile)
linear=rgb.astype(np.float32)/18000
save('rgb32-linear',linear,photometric='rgb',compression='deflate',predictor=3)
save('rgb8-jpeg',(rgb/257).astype(np.uint8),photometric='rgb',compression='jpeg',iccprofile=profile)
save('invalid-profile',rgb,photometric='rgb',iccprofile=b'not an ICC profile')
content=(out/'rgb16-deflate.tiff').read_bytes();(out/'truncated.tiff').write_bytes(content[:len(content)//2])
# Packed grayscale with odd row widths exercises byte padding at every bit depth.
import struct
for depth in [1, 2, 4]:
    w, h = 73, 5
    pixels = np.arange(w * h, dtype=np.uint8).reshape(h, w) % (1 << depth)
    payload = bytearray()
    for row in pixels:
        packed = bytearray((w * depth + 7) // 8)
        for x, v in enumerate(row): packed[x * depth // 8] |= int(v) << (8 - depth - x * depth % 8)
        payload.extend(packed)
    entries = [(256,4,w),(257,4,h),(258,3,depth),(259,3,1),(262,3,1),
               (273,4,8+2+9*12+4),(277,3,1),(278,4,h),(279,4,len(payload))]
    header = b'II' + struct.pack('<HIH',42,8,len(entries))
    for tag, kind, value in entries: header += struct.pack('<HHII',tag,kind,1,value)
    (out/f'gray{depth}-packed.tiff').write_bytes(header + struct.pack('<I',0) + payload)
# Palette expansion should equal independently stored RGB16 values.
indices = (np.arange(45*70).reshape(45,70) % 256).astype(np.uint8)
colormap = np.array([np.arange(256)*257, (255-np.arange(256))*257, (np.arange(256)*19 % 256)*257],dtype=np.uint16)
save('palette8',indices,photometric='palette',colormap=colormap,iccprofile=profile)
save('palette-reference',colormap[:,indices].transpose(1,2,0),photometric='rgb',iccprofile=profile)
(out/'manifest.json').write_text(json.dumps({'cases':cases,'width':70,'height':45,'samples':rgb.tolist()}))
print(f'Wrote {len(cases)} synthetic TIFFs in {out}')
