#!/usr/bin/env python3
"""Generate small public sRGB/Display P3 ICC resources using Little CMS 2.

No operating-system or vendor profile is copied. Display P3 coordinates and transfer:
https://registry.color.org/rgb-registry/displayp3
Set LCMS2_LIBRARY if the library is not discoverable by ctypes.
"""
import base64
import ctypes as c
import ctypes.util
import os
from pathlib import Path

library = os.environ.get('LCMS2_LIBRARY') or ctypes.util.find_library('lcms2')
if not library:
    raise SystemExit('Install Little CMS 2 or set LCMS2_LIBRARY to its shared library.')
lib = c.CDLL(library)
class xyY(c.Structure):
    _fields_ = [('x', c.c_double), ('y', c.c_double), ('Y', c.c_double)]
class Primaries(c.Structure):
    _fields_ = [('red', xyY), ('green', xyY), ('blue', xyY)]
lib.cmsCreate_sRGBProfile.restype = c.c_void_p
lib.cmsReadTag.argtypes = [c.c_void_p, c.c_uint32]
lib.cmsReadTag.restype = c.c_void_p
lib.cmsCreateRGBProfile.argtypes = [c.POINTER(xyY), c.POINTER(Primaries), c.POINTER(c.c_void_p)]
lib.cmsCreateRGBProfile.restype = c.c_void_p
lib.cmsSaveProfileToMem.argtypes = [c.c_void_p, c.c_void_p, c.POINTER(c.c_uint32)]
lib.cmsCloseProfile.argtypes = [c.c_void_p]
lib.cmsSetProfileVersion.argtypes = [c.c_void_p, c.c_double]
lib.cmsMLUalloc.argtypes = [c.c_void_p, c.c_uint32]
lib.cmsMLUalloc.restype = c.c_void_p
lib.cmsMLUsetASCII.argtypes = [c.c_void_p, c.c_char_p, c.c_char_p, c.c_char_p]
lib.cmsMLUfree.argtypes = [c.c_void_p]
lib.cmsWriteTag.argtypes = [c.c_void_p, c.c_uint32, c.c_void_p]

def tag(profile, signature, text):
    value = lib.cmsMLUalloc(None, 1)
    try:
        assert lib.cmsMLUsetASCII(value, b'en', b'US', text.encode('ascii'))
        assert lib.cmsWriteTag(profile, int.from_bytes(signature.encode('ascii'), 'big'), value)
    finally:
        lib.cmsMLUfree(value)

def encode(profile, name):
    lib.cmsSetProfileVersion(profile, 4.4)
    tag(profile, 'desc', name)
    tag(profile, 'cprt', 'No copyright, use freely')
    count = c.c_uint32()
    assert lib.cmsSaveProfileToMem(profile, None, c.byref(count))
    memory = c.create_string_buffer(count.value)
    assert lib.cmsSaveProfileToMem(profile, memory, c.byref(count))
    data = bytearray(memory.raw)
    data[24:36] = bytes.fromhex('07d000010001000000000000')  # Fixed creation date.
    data[40:44] = bytes(4)  # Platform-independent resource.
    return base64.b64encode(data).decode('ascii')

srgb = lib.cmsCreate_sRGBProfile()
curve = lib.cmsReadTag(srgb, int.from_bytes(b'rTRC', 'big'))
white = xyY(.3127, .3290, 1)
primaries = Primaries(xyY(.68, .32, 1), xyY(.265, .69, 1), xyY(.15, .06, 1))
p3 = lib.cmsCreateRGBProfile(c.byref(white), c.byref(primaries), (c.c_void_p * 3)(curve, curve, curve))
try:
    profiles = {'srgb': encode(srgb, 'sRGB'), 'display-p3': encode(p3, 'Display P3')}
finally:
    lib.cmsCloseProfile(p3)
    lib.cmsCloseProfile(srgb)
output = '// Generated by tools/generate-web-color-profiles.py from public color-space definitions.\n'
output += '// Fixed creation date; no platform profile is copied.\nconst profiles = {\n'
output += ''.join(f"  '{key}': '{value}',\n" for key, value in profiles.items())
output += '''}\nexport function iccProfile(colorSpace) {
  const encoded = profiles[colorSpace]
  if (!encoded) throw new Error('Unsupported TIFF color space.')
  return Uint8Array.from(atob(encoded), (c) => c.charCodeAt(0))
}
'''
(Path(__file__).resolve().parents[1] / 'web/src/color-profiles.js').write_text(output)
